#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=CheckEnvironment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --time=00:05:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2024
# 初始化 conda
source ~/anaconda3/etc/profile.d/conda.sh

# 激活环境
conda activate dl2024

# Check whether the GPU is available
srun python -uc "import torch; print('GPU available?', torch.cuda.is_available())"
