#!/bin/bash

# ----------- SLURM 指令（保留必要部分） ------------
#SBATCH --job-name=generate_gt_image
#SBATCH --partition=gpu_mig
#SBATCH --gres=gpu:1
#SBATCH --time=06:00:00
#SBATCH --mem=16G
#SBATCH --cpus-per-task=8
#SBATCH --output=logs_out/trans_bvm_test_%j.out
#SBATCH --error=logs_err/trans_bvm_test_%j.err

# 创建日志目录
mkdir -p logs_out logs_err

# 加载执行环境
module purge
module load 2024
source ~/anaconda3/etc/profile.d/conda.sh
source activate dl2024 || { echo "Failed to activate Conda env"; exit 1; }

python ijmond-camera-ai/bvm_training/trans_bvm_self_supervised/test.pydels/finetune/Model_50_gen_no_pretrained_weights.pth --method supervised --test_dataset ijmond