#!/bin/bash

# ----------- SLURM directives (keep necessary parts) ------------
#SBATCH --job-name=test_bvm_semi_supervised
#SBATCH --partition=gpu_h100
#SBATCH --gres=gpu:1
#SBATCH --time=01:00:00
#SBATCH --mem=16G
#SBATCH --cpus-per-task=4
#SBATCH --output=../logs_out/_crop_semi_test_%j.out
#SBATCH --error=../logs_err/_crop_semi_test_%j.err

# Load execution environment
module purge
module load 2024
source ~/anaconda3/etc/profile.d/conda.sh
source activate dl2024 || { echo "Failed to activate Conda env"; exit 1; }

# Switch to project root directory
cd "$(dirname "$0")/.."

# Create log directories
mkdir -p logs_out logs_err

# Run semi-supervised model test
# --model_path: Path to the semi-supervised trained model
# --test_dataset: Test dataset (smoke5k)
python src/bvm_training/trans_bvm_self_supervised/test.py \
--model_path models/semi-supervision/SMOKE5K-ijmond-camera-on-SMOKE5K/SMOKE5K_Dataset_SMOKE5K_train_ssl_ijmond_camera_SMOKE5K-full_citizen_constraint/SMOKE5K_Dataset_SMOKE5K_train_ssl_ijmond_camera_SMOKE5K-full_citizen_constraint_epoch_020_from_scratch.pth \
--test_dataset ijmond \