#!/bin/bash

# ----------- SLURM directives (keep necessary parts) ------------
#SBATCH --job-name=test_bvm_thesis
#SBATCH --partition=gpu_h100
#SBATCH --gres=gpu:1
#SBATCH --time=03:00:00
#SBATCH --mem=32G
#SBATCH --cpus-per-task=6
#SBATCH --output=../logs_out/test_thesis_domain_adapt_%j.out
#SBATCH --error=../logs_err/test_thesis_domain_adapt_%j.err

# ============================================================================
# BVM thesis version domain adaptation model test script
# ============================================================================

# Load execution environment
module purge
module load 2024
source ~/anaconda3/etc/profile.d/conda.sh
source activate dl2024 || { echo "Failed to activate Conda env"; exit 1; }

# Switch to project root directory
cd "$(dirname "$0")/.."

# Create log directories
mkdir -p logs_out logs_err

# Run thesis version domain adaptation model test
python src/bvm_training/trans_bvm_self_supervised_thesis/test.py \
--model_path models/thesis/gold/SMOKE5K_Dataset_SMOKE5K_train_to_ijmond_data_train_da/SMOKE5K_Dataset_SMOKE5K_train_to_ijmond_data_train_da_best_model.pth \
--test_dataset ijmond \
--use_ldconv \
--use_attention_pool