#!/bin/bash

# ----------- SLURM directives (keep necessary parts) ------------
#SBATCH --job-name=test_bvm_supervised
#SBATCH --partition=gpu_mig
#SBATCH --gres=gpu:1
#SBATCH --time=02:00:00
#SBATCH --mem=16G
#SBATCH --cpus-per-task=4
#SBATCH --output=../logs_out/test_bvm_supervised_%j.out
#SBATCH --error=../logs_err/test_bvm_supervised_%j.err

# ============================================================================
# BVM supervised model test script
# ============================================================================

# Load execution environment
module purge
module load 2024
source ~/anaconda3/etc/profile.d/conda.sh
source activate dl2024 || { echo "Failed to activate Conda env"; exit 1; }

# Switch to project root directory
cd "$(dirname "$0")/.."

# Create log directories
mkdir -p logs_out logs_err

# Run supervised model test
python src/bvm_training/trans_bvm/test.py \
--model_path models/full-supervision/SMOKE5K-supervised/SMOKE5K_Dataset_SMOKE5K_train/SMOKE5K_Dataset_SMOKE5K_train_best_model.pth \
--test_dataset ijmond